#!/usr/bin/env bash
# Mix the soundtrack from the LibreOffice gallery samples and embed it for the page.
# Needs python3 + numpy and ffmpeg (FFMPEG=/path/to/ffmpeg to override).
set -euo pipefail
cd "$(dirname "$0")/.."
FFMPEG=${FFMPEG:-ffmpeg}
python3 tools/mix.py soundtrack.wav
"$FFMPEG" -loglevel error -y -i soundtrack.wav -c:a libmp3lame -b:a 160k soundtrack.mp3
python3 - <<'PY'
import base64
b = base64.b64encode(open("soundtrack.mp3", "rb").read()).decode()
open("soundtrack.js", "w").write("// Generated by tools/build-audio.sh from soundtrack.mp3\nwindow.SOUNDTRACK_MP3 = \"" + b + "\";\n")
PY
echo "soundtrack.mp3 and soundtrack.js updated"
